// Array of Valentine quotes
const quotes = [
    "Love is not about how many days, but how much love you give every day. 💖",
    "You are my sunshine on a rainy day. 🌞🌧️",
    "Every love story is beautiful, but ours is my favorite. 💕",
    "Love is composed of a single soul inhabiting two bodies. 💑",
    "To love and be loved is to feel the sun from both sides. ☀️❤️",
    "You are my forever and always. 💍",
    "In all the world, there is no heart for me like yours. 💘",
    "Love is a friendship set to music. 🎶💖",
    "I never want to stop making memories with you. 📸❤️",
    "You're the peanut butter to my jelly. 🥜🍇",
    "I love you to the moon and back. 🌙💫",
    "You are my today and all of my tomorrows. 💫",
    "The best thing to hold onto in life is each other. 🤝💑",
    "Together is a wonderful place to be. 🌍💞",
    "When I follow my heart, it leads me to you. 💓",
    "You had me at hello. 👋❤️",
    "Every moment with you is like a beautiful dream come true. 🌹💭",
    "Home is wherever I'm with you. 🏡❤️",
    "I love you more than I have ever found a way to say to you. 💌",
    "My heart is, and always will be, yours. 💝",
    "You're my favorite distraction. 💫💕",
    "I need you like a heart needs a beat. 💓🎶",
    "I would rather spend one lifetime with you, than face all the ages of this world alone. ⏳❤️",
    "You're the reason I smile every day. 😊❤️",
    "You are my happily ever after. 🏰💖",
    "I didn't choose you, my heart did. ❤️💘",
    "Every time I see you, I fall in love all over again. 😍💞",
    "You are the one I’ve been waiting for. ⏳💖",
    "You make me a better person. 🥰✨",
    "You complete me. 💑💖",
    "Love you more than pizza. 🍕❤️",
    "With you, I am home. 🏡💖",
    "You are the reason I believe in love. 💘✨",
    "I’m much more me when I’m with you. 💓",
    "My love for you is a journey, starting at forever and ending at never. 💕",
    "You are my today and all of my tomorrows. 🌅💖",
    "The best thing about me is you. 💑❤️",
    "You make my heart skip a beat. 💓💨",
    "I love you more than words can express. 💌💖",
    "You are the light in my life. 💡❤️",
    "I’m so grateful to have you by my side. 🙏💖",
    "You’re my favorite person in the world. 🌍❤️",
    "I could spend forever with you and still never get tired of you. ⏳💘",
    "You're the one I want to grow old with. 👴👵💖",
    "You are my dream come true. 🌟💖",
    "Every day with you is my favorite day. 🗓️💖",
    "You are my happily ever after. 🏰💓",
    "You're the best part of my day. ☀️💖",
    "I never want to stop making memories with you. 📸💞",
    "I could get lost in your eyes forever. 👀💖",
    "You make my world brighter. 🌞💓",
    "I'm falling for you more and more every day. 💖",
    "You make everything better just by being you. 🌟❤️",
    "Being in your arms feels like home. 🏡💖",
    "You are my best friend and my love. 💞👫",
    "Love isn't perfect, but with you, it's pretty close. 💑💖",
    "I feel safe when I'm with you. 🛡️❤️",
    "You bring out the best in me. 💖✨",
    "You are the person I want to spend forever with. ⏳💍",
    "I am so lucky to call you mine. 🍀💖",
    "Every second spent with you is a second well spent. ⏱️💓",
    "You're the reason I look forward to every day. 🌞💖",
    "I just want to hold your hand forever. 🤲💖",
    "You are the calm to my storm. 🌪️💖",
    "You are the love of my life. 💕🌍",
    "No matter where life takes us, we’ll be together. 🌎💑",
    "You make me feel like the luckiest person in the world. 🍀❤️",
    "I love the way you love me. 🥰💖",
    "You and me, together forever. 💑🌟",
    "Your smile makes my heart melt. 😊💓",
    "I can’t wait to spend forever with you. 💍❤️",
    "When I’m with you, everything else fades away. 🌅💖",
    "I love you more than I ever thought was possible. 💘",
    "You’re my favorite place to be. 🏡❤️",
    "You make everything better. 💖🌈",
    "In your eyes, I see forever. 👀💍",
    "You're the only one I want to grow old with. 👵👴💖",
    "With you, I’ve found my forever. 💕💍",
    "Every day with you feels like a dream. 🌙💖",
    "I love the way you make me feel. 💖✨",
    "You’re my happy place. 🌸💖",
    "I’ll love you forever, no matter what. 💘",
    "My heart belongs to you. 💖🔒",
    "Your love is my greatest adventure. 🗺️💖",
    "You’re the reason I believe in magic. ✨❤️",
    "My world is better with you in it. 🌍💖",
    "I would do anything to make you happy. 💖😊",
    "You complete the puzzle of my heart. 🧩💘",
    "I love you not only for who you are but for who I am when I’m with you. 💕",
    "With you, I am always at peace. ✌️💖",
    "You're the best part of my life. 💖🌟",
    "You make me feel alive in a way I never have before. 💓✨",
    "I feel like the luckiest person when I’m with you. 🍀❤️",
    "You are my heart’s home. 💖🏡",
    "You are my greatest gift. 🎁💖",
    "I never knew love until I met you. 💖💫",
    "You are the missing piece of my heart. 💔💖",
    "No one else will ever be as perfect for me as you are. 💞💖",
    "Every moment with you is a treasure. 💎❤️",
    "I love you more than words can ever say. 💌💘",
    "You are my reason to smile. 😊❤️",
    "You're my favorite hello and my hardest goodbye. 👋💔",
    "You are the light of my life. 🌟💖",
    "When I’m with you, I’m home. 🏡💖",
    "I’m forever grateful for your love. 🙏💘",
    "I love you like the stars love the night sky. 🌌💖",
    "You're my once-in-a-lifetime. 🌟💑",
    "You’re the dream I never want to wake up from. 🌙💖",
    "I could spend every day for the rest of my life with you. ⏳💘",
    "I will always love you, no matter what. 💖"
];


// Get elements
const quoteElement = document.getElementById("quote");
const button = document.getElementById("new-quote-btn");

// Function to change the quote
function getRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    quoteElement.textContent = quotes[randomIndex];
}

// Event listener for the button
button.addEventListener("click", getRandomQuote);
